version: "3.9"

services:
  whisper-api:
    image: didmar/whisper-api-server
    build: .
    container_name: whisper-api-server
    restart: unless-stopped
    init: true
    volumes:
      - ./.cache:/root/.cache
    command: --workers 1
    ports:
      - 8000:8000
